baseURL = "http://dukehugo.s3-website-us-east-1.amazonaws.com"
languageCode = "en-us"
title = "Shyamal Anadkat"
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://dukehugo/?region=us-east-1" #your bucket here